version: '3.8'

services:

  db:
    container_name: database
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile-php
      target: php-fpm
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
